"""Wake-word pipeline components for Lumivox."""

from .stream import (
    InputChunk,
    OutputChunk,
    StreamError,
    StreamConfig,
    StreamProcessor,
    VadPolicyConfig,
    StreamCloseError,
    StreamStateError,
    WakePolicyConfig,
    StreamProcessingError,
)
from ._processor import WakeStreamProcessor
from .diagnostics import (
    DiagnosticDrain,
    DiagnosticEvent,
    RearmDiagnostic,
    FailureDiagnostic,
    VadFrameDiagnostic,
    VadSpeechDiagnostic,
    VadTransitionReason,
    WakeFrameDiagnostic,
    ActivationDiagnostic,
    WakeCandidateEndReason,
    ContinuityBoundaryReason,
    DiagnosticFailureOperation,
    ContinuityBoundaryDiagnostic,
    WakeCandidateEndedDiagnostic,
    WakeCandidateStartedDiagnostic,
)

__all__ = [
    "ActivationDiagnostic",
    "ContinuityBoundaryDiagnostic",
    "ContinuityBoundaryReason",
    "DiagnosticDrain",
    "DiagnosticEvent",
    "DiagnosticFailureOperation",
    "FailureDiagnostic",
    "InputChunk",
    "OutputChunk",
    "RearmDiagnostic",
    "StreamCloseError",
    "StreamConfig",
    "StreamError",
    "StreamProcessingError",
    "StreamProcessor",
    "StreamStateError",
    "VadPolicyConfig",
    "VadFrameDiagnostic",
    "VadSpeechDiagnostic",
    "VadTransitionReason",
    "WakeCandidateEndedDiagnostic",
    "WakeCandidateEndReason",
    "WakeCandidateStartedDiagnostic",
    "WakeFrameDiagnostic",
    "WakePolicyConfig",
    "WakeStreamProcessor",
]
